# Site settings
title: Sterling Brick & Stone
email: your-email@domain.com
url: https://radivoi.github.io/STERLING/
description: "Sterling Brick & Stone is a family owned and operated business serving the Waterloo region. We specialize in all types of masonry work, including brick, stone, and concrete. Our team of skilled craftsmen are dedicated to providing the highest quality workmanship and customer service. Whether you need a new patio, walkway, or retaining wall, we have the experience and expertise to get the job done right."
baseurl: ""
author: "Michael Radivoi"
author_email: "michaelradivoi@gmail.com"
keywords: "your keywords, separated by commas"
skills: "Stone Mason - Bricklayer - Concrete Specialist - Masonry Repair Expert"
meta_author: LastName FirstName

#
# Google webmaster tools
#google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
#bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
#contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
#disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: FFFFFF
  primary-rgb: "226,199,153"
  secondary: 1A1A1A
  secondary-dark: 8F2D02

# Footer settings
footer:
  copyright: 2025 Sterling Masonry
  location: Waterloo, Ontario, Canada
  social: Around the Web
#  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Credits content
#credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
